### ISSUE TITLE
Не стартует, не может смонтировать 

### ISSUE THREAD

**Issue by grevinden** [alexanderfefelov/docker-postgrespro-1c#5]
Failure
OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/676b0151e5f4781f81e1f5c98a70266fb25ca5aaedb66fa9ead81bd01aa72118/merged\\\" at \\\"/var/lib/docker/overlay2/676b0151e5f4781f81e1f5c98a70266fb25ca5aaedb66fa9ead81bd01aa72118/merged/usr/share/zoneinfo/Zulu\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by alexanderfefelov** [comment]
Что я должен сделать, чтобы воспроизвести эту проблему? Приведите пошаговую инструкцию.

**Comment by grevinden** [comment]
я просто выполняю вашу инструкцию и получаю такой результат
`git clone https://github.com/alexanderfefelov/docker-postgrespro-1c.git`
`cd docker-postgrespro-1c`
`./build.sh`
`./run.sh`

и еще вопрос: можно обновить версию до PG96?

**Comment by alexanderfefelov** [comment]
Я только что проверил на своём стенде. У меня всё работает.

Дайте больше деталей: версии OS и Docker, последовательность действий, цитаты из логов.

**Comment by grevinden** [comment]
Linux acer 4.14.73-rancher #1 SMP Thu Oct 4 00:19:21 UTC 2018 x86_64 Linux
просто поставьте в docker rancheros и попробуйте на ней собрать.

**Comment by alexanderfefelov** [comment]
А причём здесь Rancher? Я нигде не упоминал его. 

Кроме того: https://github.com/rancher/os/issues/2218

**Comment by grevinden** [comment]
`sudo ros config set rancher.services.console.environment.TZ "Europe/Moscow"`
вопрос решился, спасибо
